### DISCUSSION TITLE
Hide event description/body

### DISCUSSION THREAD

**Discussion by devin1229** [MMRIZE/MMM-CalendarExt3Journal#9] [Q&A]
Basically the title - is there any way to hide the event descriptions from view? I have a iCal file and it's pulling in both the meeting body text as well as location (if defined in the event).

**Comment by eouia** [comment]
```css
/* css/custom.css */
.CX3J .event .description,
.CX3J .event .location {
  display: none;
}
```

**BEFORE**

<img width="954" alt="image" src="https://github.com/user-attachments/assets/d6ee8a27-266d-4426-96b7-768758c7b65f" />


**AFTER**

<img width="954" alt="image" src="https://github.com/user-attachments/assets/4cf9352a-bb20-4bd2-8abd-27e50e9c21e0" />
